In [22]:
import pandas as pd

In [23]:

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

In [24]:
#Display the last 7 rows of the DataFrame `df` to get an initial look at the data.
df.tail(7)

,order_id,quantity,item_name,choice_description,item_price
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [25]:
#Print a summary of the DataFrame including the index dtype and column dtypes, non-null values, and memory usage. Comment on what you see.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [26]:
#Determine how many observations have missing item_price in the dataset.
df_missing_items = df['item_price'].isnull().sum()
print(f"Missing item_price: {df_missing_items}")

Missing item_price: 0

In [27]:
#Print the names of all columns in the DataFrame.
df_columns = df.columns
print(f"Column names: {df_columns}")

Column names: Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [28]:
#Identify which `item_name` appears most frequently in the orders.
df_most_frequent_item = df['item_name'].value_counts().idxmax()
print(f"Most frequent item: {df_most_frequent_item}")

Most frequent item: Chicken Bowl

In [29]:
# Determine how many distinct `item_name` values are present in the dataset.
df_distinct_items = df['item_name'].nunique()
print(f"Distinct item_name values: {df_distinct_items}")

Distinct item_name values: 50

In [30]:
#Create a new DataFrame containing only the rows where the `item_name` is 'Chicken Bowl'
df_chicken_bowl = df[df['item_name'] == 'Chicken Bowl']
df_chicken_bowl

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75

In [32]:
#The 'item\_price' column is currently a string (e.g., '$2.39'). Convert it to a float type. You'll need to remove the dollar sign and then convert the data type.

df['item_price'] = df['item_price'].str.replace('$', '').astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [33]:
#After converting 'item\_price' to a numerical type, calculate the average `item_price` across all orders.
average_item_price = df['item_price'].mean()
print(f"Average item_price: {average_item_price:.2f}")

Average item_price: 7.46

In [34]:
#Determine the total number of unique orders in the dataset based on the `order_id` column.
total_unique_orders = df['order_id'].nunique()
print(f"Total unique orders: {total_unique_orders}")

Total unique orders: 1834

In [35]:
# **Total Revenue Calculation (Pandas)**

# Assuming each `item_price` (after conversion to float) is for a single quantity of that item, calculate the total revenue generated from all orders. Remember that the `quantity` column indicates how many of that `item_name` were ordered in that specific line item.
df['revenue'] = df['item_price'] * df['quantity']
total_revenue = df['revenue'].sum()
print(f"Total revenue: ${total_revenue:.2f}")

Total revenue: $39237.02